### ISSUE TITLE
Self signed certificate for email

### ISSUE THREAD

**Issue by dpineiden** [docker-taiga/taiga#52]
Hi guys!

I'm runing ok the docker container for taiga and penpot, but i have problems with the email side. I put all the data correctly and test with an script. But the email has a self signed certificate, maybe because that the site doesn't send anything, there are a way to enable the ss certificate?

Thanks best regards!

**Comment by dpineiden** [comment]
Hi.
In the taiga now i can run fine, declaring the variables only on the *-inits.yml file.

On the penpot application with my self-signed email, shows me this error

```
penpot-backend_1   | [worker-49] D app.worker - started task 'sendmail/e7fb75c0-7c95-11eb-8387-c1f90d1c23eb/0'
penpot-backend_1   | [worker-49] E app.worker - unhandled exception on task (id: 'eb6358e0-7c95-11eb-8387-c1f90d1c23eb')
penpot-backend_1   | jakarta.mail.MessagingException: Could not convert socket to TLS
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2140) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:734) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Service.connect(Service.java:342) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Service.connect(Service.java:222) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Service.connect(Service.java:243) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Transport.send0(Transport.java:228) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Transport.send(Transport.java:150) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at app.util.emails$send_BANG_.invokeStatic(emails.clj:174) ~[?:?]
penpot-backend_1   | 	at app.util.emails$send_BANG_.invoke(emails.clj:171) ~[?:?]
penpot-backend_1   | 	at app.tasks.sendmail$eval34961$fn__34962$fn__34964.invoke(sendmail.clj:45) ~[?:?]
penpot-backend_1   | 	at app.metrics$wrap_summary$fn__5164.invoke(metrics.clj:263) ~[?:?]
penpot-backend_1   | 	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RestFn.applyTo(RestFn.java:132) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at app.worker$handle_task.invokeStatic(worker.clj:206) ~[?:?]
penpot-backend_1   | 	at app.worker$handle_task.invoke(worker.clj:202) ~[?:?]
penpot-backend_1   | 	at app.worker$run_task.invokeStatic(worker.clj:241) [?:?]
penpot-backend_1   | 	at app.worker$run_task.invoke(worker.clj:237) [?:?]
penpot-backend_1   | 	at app.tasks$instrument_BANG_$fn__25850$fn__25851.invoke(tasks.clj:84) [?:?]
penpot-backend_1   | 	at clojure.lang.AFn.applyToHelper(AFn.java:156) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core$partial$fn__5860.invoke(core.clj:2634) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at promesa.util.SupplierWrapper.get(util.cljc:37) [?:?]
penpot-backend_1   | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) [?:?]
penpot-backend_1   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773) [jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
penpot-backend_1   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905) [jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
penpot-backend_1   | 	at java.lang.Thread.run(Thread.java:832) [?:?]
penpot-backend_1   | Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
penpot-backend_1   | 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:369) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:312) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:307) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:199) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
penpot-backend_1   | 	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:529) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2135) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	... 29 more
penpot-backend_1   | Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
penpot-backend_1   | 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439) ~[?:?]
penpot-backend_1   | 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
penpot-backend_1   | 	at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:199) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
penpot-backend_1   | 	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:529) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2135) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	... 29 more
penpot-backend_1   | Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
penpot-backend_1   | 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[?:?]
penpot-backend_1   | 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[?:?]
penpot-backend_1   | 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[?:?]
penpot-backend_1   | 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434) ~[?:?]
penpot-backend_1   | 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
penpot-backend_1   | 	at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:199) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
penpot-backend_1   | 	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:529) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2135) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	... 29 more
penpot-backend_1   | [worker-49] D app.worker - finished task 'sendmail/e7fb75c0-7c95-11eb-8387-c1f90d1c23eb/0'
penpot-backend_1   | [worker-45] D app.worker - started task 'sendmail/e7fb75c0-7c95-11eb-8387-c1f90d1c23eb/1'
penpot-backend_1   | [worker-45] E app.worker - unhandled exception on task (id: 'f32435e0-7c95-11eb-8387-c1f90d1c23eb')
penpot-backend_1   | jakarta.mail.MessagingException: Could not convert socket to TLS
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2140) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:734) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Service.connect(Service.java:342) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Service.connect(Service.java:222) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Service.connect(Service.java:243) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Transport.send0(Transport.java:228) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Transport.send(Transport.java:150) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at app.util.emails$send_BANG_.invokeStatic(emails.clj:174) ~[?:?]
penpot-backend_1   | 	at app.util.emails$send_BANG_.invoke(emails.clj:171) ~[?:?]
penpot-backend_1   | 	at app.tasks.sendmail$eval34961$fn__34962$fn__34964.invoke(sendmail.clj:45) ~[?:?]
penpot-backend_1   | 	at app.metrics$wrap_summary$fn__5164.invoke(metrics.clj:263) ~[?:?]
penpot-backend_1   | 	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RestFn.applyTo(RestFn.java:132) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at app.worker$handle_task.invokeStatic(worker.clj:206) ~[?:?]
penpot-backend_1   | 	at app.worker$handle_task.invoke(worker.clj:202) ~[?:?]
penpot-backend_1   | 	at app.worker$run_task.invokeStatic(worker.clj:241) [?:?]
penpot-backend_1   | 	at app.worker$run_task.invoke(worker.clj:237) [?:?]
penpot-backend_1   | 	at app.tasks$instrument_BANG_$fn__25850$fn__25851.invoke(tasks.clj:84) [?:?]
penpot-backend_1   | 	at clojure.lang.AFn.applyToHelper(AFn.java:156) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core$partial$fn__5860.invoke(core.clj:2634) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at promesa.util.SupplierWrapper.get(util.cljc:37) [?:?]
penpot-backend_1   | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) [?:?]
penpot-backend_1   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773) [jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
penpot-backend_1   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905) [jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
penpot-backend_1   | 	at java.lang.Thread.run(Thread.java:832) [?:?]
penpot-backend_1   | Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
penpot-backend_1   | 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:369) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:312) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:307) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:199) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
penpot-backend_1   | 	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:529) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2135) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	... 29 more
penpot-backend_1   | Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
penpot-backend_1   | 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439) ~[?:?]
penpot-backend_1   | 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
penpot-backend_1   | 	at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:199) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
penpot-backend_1   | 	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:529) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2135) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	... 29 more
penpot-backend_1   | Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
penpot-backend_1   | 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[?:?]
penpot-backend_1   | 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[?:?]
penpot-backend_1   | 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[?:?]
penpot-backend_1   | 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434) ~[?:?]
penpot-backend_1   | 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
penpot-backend_1   | 	at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:199) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
penpot-backend_1   | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
penpot-backend_1   | 	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:529) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2135) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	... 29 more
penpot-backend_1   | [worker-45] D app.worker - finished task 'sendmail/e7fb75c0-7c95-11eb-8387-c1f90d1c23eb/1'

```
